export {
  defaultEraConfig,
  defaultEraDisplayNames,
  defaultTimelineViewConfig,
  extractEraConfig,
  getDefaultEraRanges,
  getEraClasses,
  getEraConfigForYear,
  getEraDisplayName,
  getEraFromYear,
  getTimelineStatistics,
  groupEventsByEra,
  type EraConfig,
  type EraConfigMap,
  type TimelineEvent,
  type TimelineViewConfig,
} from '@merkin/blog-core/services/TimelineConfig'
